---

- name: Configure digital rebar admin node
  hosts: group_digitalrebar
  roles:
    - stanchan.dr-provision
  vars:
    provision_release_tag: v3.13.5
    provision_content_release_tag: v1.13.1

    provision_delete_default_user: yes
  
    provision_options:
      disable-tftp: no
      disable-provisioner: no
      disable-dhcp: no
      disable-pxe: no
      static-port: 8091
      tftp-port: 69
      api-port: 8092
      dhcp-port: 67
      binl-port: 4011
      unknown-token-timeout: 600
      known-token-timeout: 3600
      static-ip: null
      force-static: no
      backend: directory
      local-content: directory:///etc/dr-provision?codec=yaml
      default-content: file:///usr/share/dr-provision/default.yaml?codec=yaml
      base-root: "{{ provision_var_dir }}"
      data-root: digitalrebar
      plugin-root: plugins
      log-root: job-logs
      saas-content-root: saas-content
      file-root: tftpboot
      replace-root: replace
      local-ui: ux
      ui-url: https://portal.rackn.io
      dhcp-ifs: no
      default-stage: none
      default-boot-env: local
      unknown-boot-env: ignore
      debug-bootenv: warn
      debug-dhcp: warn
      debug-renderer: warn
      debug-frontend: warn
      debug-plugins: warn
      tls-key: server.key
      tls-cert: server.crt
      use-old-ciphers: no
      drp-id: no
      cert-type: P384
      base-token-secret: no
      system-grantor-secret: no
      log-level: warn
    
    provision_preferences: 
      unknownBootEnv: discovery
      defaultBootEnv: sledgehammer
      defaultStage: discover

    provision_content_release:
      - name: drp-community-content
        override:
          sections:
            bootenvs:
              discovery:
                OS:
                  SupportedArchitectures: 
                    amd64:
                      IsoFile: sledgehammer-c7305a9ba2c6b12351530c4a9021fd5e07ef1ce1.amd64.tar
                      IsoUrl: http://nexus.talifun.com/repository/iso-hosted/sledgehammer-c7305a9ba2c6b12351530c4a9021fd5e07ef1ce1.amd64.tar
                      IsoSha256: ''
                    arm64:
                      IsoFile: sledgehammer-9b5276ac5826520829aa73c149fe672fe2363656.arm64.tar
                      IsoUrl: http://nexus.talifun.com/repository/iso-hosted/sledgehammer-9b5276ac5826520829aa73c149fe672fe2363656.arm64.tar       
                      IsoSha256: '' 
              sledgehammer:
                OS:
                  SupportedArchitectures: 
                    amd64:
                      IsoFile: sledgehammer-c7305a9ba2c6b12351530c4a9021fd5e07ef1ce1.amd64.tar
                      IsoUrl: http://nexus.talifun.com/repository/iso-hosted/sledgehammer-c7305a9ba2c6b12351530c4a9021fd5e07ef1ce1.amd64.tar
                      IsoSha256: ''
                    arm64:
                      IsoFile: sledgehammer-9b5276ac5826520829aa73c149fe672fe2363656.arm64.tar
                      IsoUrl: http://nexus.talifun.com/repository/iso-hosted/sledgehammer-9b5276ac5826520829aa73c149fe672fe2363656.arm64.tar  
                      IsoSha256: ''
              centos-7-install:
                OS:
                  SupportedArchitectures: 
                    aarch64:
                      IsoFile: CentOS-7-aarch64-Minimal-1810.iso
                      IsoUrl: http://nexus.talifun.com/repository/iso-hosted/CentOS-7-aarch64-Minimal-1810.iso
                      IsoSha256: ''
                    x86_64:
                      IsoFile: CentOS-7-x86_64-Minimal-1810.iso
                      IsoUrl: http://nexus.talifun.com/repository/iso-hosted/CentOS-7-x86_64-Minimal-1810.iso   
                      IsoSha256: ''
              centos-7.6.1810-install:
                OS:
                  SupportedArchitectures: 
                    aarch64:
                      IsoFile: CentOS-7-aarch64-Minimal-1810.iso
                      IsoUrl: http://nexus.talifun.com/repository/iso-hosted/CentOS-7-aarch64-Minimal-1810.iso
                      IsoSha256: ''
                    x86_64:
                      IsoFile: CentOS-7-x86_64-Minimal-1810.iso
                      IsoUrl: http://nexus.talifun.com/repository/iso-hosted/CentOS-7-x86_64-Minimal-1810.iso   
                      IsoSha256: ''              
              debian-8-install:
                OS:
                  IsoFile: debian-8-amd64-mini.iso
                  IsoUrl: http://nexus.talifun.com/repository/iso-hosted/debian-8-amd64-mini.iso
                  IsoSha256: ''                       
              debian-9-install:
                OS:
                  IsoFile: debian-9-amd64-mini.iso
                  IsoUrl: http://nexus.talifun.com/repository/iso-hosted/debian-9-amd64-mini.iso
                  IsoSha256: ''
              ubuntu-16.04-install:
                OS:
                  IsoFile: ubuntu-16.04.6-server-amd64.iso
                  IsoUrl: http://nexus.talifun.com/repository/iso-hosted/ubuntu-16.04.6-server-amd64.iso
                  IsoSha256: ''
              ubuntu-18.04-install:
                OS:
                  SupportedArchitectures: 
                    amd64:
                      IsoFile: ubuntu-18.04.2-server-amd64.iso
                      IsoUrl: http://nexus.talifun.com/repository/iso-hosted/ubuntu-18.04.2-server-amd64.iso
                      IsoSha256: ''
                    arm64:
                      IsoFile: ubuntu-18.04.2-server-arm64.iso
                      IsoUrl: http://nexus.talifun.com/repository/iso-hosted/ubuntu-18.04.2-server-arm64.iso   
                      IsoSha256: ''  
              ubuntu-18.04-arm64-hwe-install:
                OS:
                  SupportedArchitectures: 
                    arm64:
                      IsoFile: ubuntu-18.04.2-server-arm64.iso
                      IsoUrl: http://nexus.talifun.com/repository/iso-hosted/ubuntu-18.04.2-server-arm64.iso
                      IsoSha256: ''
      - name: drp-community-contrib
        override:
          sections:
            bootenvs:
              centos-6-install:
                OS:
                  IsoFile: CentOS-6.10-x86_64-bin-DVD1.iso
                  IsoUrl: http://nexus.talifun.com/repository/iso-hosted/CentOS-6.10-x86_64-bin-DVD1.iso
                  IsoSha256: ''
              centos-6.10-install:
                  IsoFile: CentOS-6.10-x86_64-bin-DVD1.iso
                  IsoUrl: http://nexus.talifun.com/repository/iso-hosted/CentOS-6.10-x86_64-bin-DVD1.iso
                  IsoSha256: ''
              centos-6.9-install:   
                  IsoFile: CentOS-6.9-x86_64-bin-DVD1.iso
                  IsoUrl: http://nexus.talifun.com/repository/iso-hosted/CentOS-6.9-x86_64-bin-DVD1.iso
                  IsoSha256: ''    
              centos-7.3.1611-install:
                  IsoFile: CentOS-7-x86_64-Minimal-1611.iso
                  IsoUrl: http://nexus.talifun.com/repository/iso-hosted/CentOS-7-x86_64-Minimal-1611.iso
                  IsoSha256: ''                                   
              scientificlinux-6.8-install:
                OS:
                  IsoFile: SL-68-x86_64-2016-06-29-DVD-DL.iso
                  IsoUrl: http://nexus.talifun.com/repository/iso-hosted/SL-68-x86_64-2016-06-29-DVD-DL.iso
                  IsoSha256: '' 
              ubuntu-14.04-install:
                OS:
                  IsoFile: ubuntu-14.04.5-server-amd64.iso
                  IsoUrl: http://nexus.talifun.com/repository/iso-hosted/ubuntu-14.04.5-server-amd64.iso
                  IsoSha256: ''        
      - name: krib
      - name: sledgehammer-builder

    provision_content_bootenvs:
      - Name: sledgehammer
        install_iso: no
      - Name: discovery
        install_iso: no
      - Name: centos-7-install
        install_iso: no
      - Name: debian-9-install
        install_iso: no
      - Name: ubuntu-16.04-install
        install_iso: no
      - Name: ubuntu-18.04-install
        install_iso: no

    provision_files_bootenvs_path: "{{ inventory_dir.split('/')[0:-2]|join('/') }}/dr-provision/bootenvs"
    provision_bootenvs_files: []
    provision_files_templates_path: "{{ inventory_dir.split('/')[0:-2]|join('/') }}/dr-provision/templates"
    provision_templates_files: []

    provision_profiles: []

    provision_machines: []

    provision_subnets:
      - Name: eth1
        ActiveEnd: 172.16.255.254
        ActiveLeaseTime: 60
        ActiveStart: 172.16.0.10
        Available: true
        Description: ''
        Enabled: true
        Errors: []
        Meta: {}
        NextServer: '172.16.0.1'
        OnlyReservations: false
        Options:
        - Code: 3
          Value: 172.16.0.1
        - Code: 6
          Value: 172.16.0.1
        - Code: 15
          Value: talifun.com
        - Code: 1
          Value: 255.255.0.0
        - Code: 28
          Value: 172.16.255.255
        Pickers:
        - hint
        - nextFree
        - mostExpired
        Proxy: false
        ReadOnly: false
        ReservedLeaseTime: 7200
        Strategy: MAC
        Subnet: 172.16.0.1/16
        Unmanaged: false
        Validated: true





    

